"""
Alloy + LLM Verification Full Pipeline

- The LLM ONLY generates/repairs the 'GeneratedPlan' predicate
- compare.als is NEVER structurally modified
- Alloy is used as a safety measure:
    SAFE = "No instance found" (no violating behavior exists)
"""
from anthropic import Anthropic
from dotenv import load_dotenv
import os
import re
import subprocess

BASE = os.path.dirname(os.path.abspath(__file__))
JAVA_DIR = os.path.join(BASE, "AlloyCommandline")
JAR = os.path.join(JAVA_DIR, "alloy4.2.jar")
JAVA_FILE = os.path.join(JAVA_DIR, "AlloyCommandline.java")
CLASS_FILE = os.path.join(JAVA_DIR, "AlloyCommandline.class")
BASE = os.path.dirname(os.path.abspath(__file__))
classpath = f"{BASE}/AlloyCommandline:{BASE}/AlloyCommandline/alloy4.2.jar"
COMPARE_PATH = "Alloy_Verifier/compare.als"

load_dotenv()
client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# Calling Claude with the prompt 
def call_claude(prompt, max_new_tokens=4000, temperature=0.7):
    message = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=max_new_tokens, # how long the response can be (one token is roughly 4 characters, so 200 tokens is about 800 characters)
        temperature=temperature, # randomness (0 = deterministic, higher temperature = more random)
        messages=[
            {"role": "user", "content": prompt}
        ],
    )
    # log AI outputs
    with open("ai_log.txt", "a") as f:
        f.write(message.content[0].text + "\n\n" + "="*60 + "\n\n")

    return message.content[0].text

# extractig the generated plan from the Alloy compare file 

def extract_generated_plan(code):
    match = re.search(r"pred\s+GeneratedPlan\s*\{.*?\}", code, re.DOTALL)
    return match.group(0) if match else None

# replacing the generated plan from the Alloy compare file with the new plan generated by the LLM
def replace_generated_plan(original_code, new_plan):
    return re.sub(
        r"pred\s+GeneratedPlan\s*\{.*?\}",
        new_plan.strip(),
        original_code,
        flags=re.DOTALL,
    )

# Save the argument content to a file at the specified path and return the path.
def save_file(content, path):
    with open(path, "w") as f:
        f.write(content)
    return path


# Run Alloy on the given file path and return a tuple of (success, output, status).
def run_alloy(file_path):
    file_path = os.path.abspath(file_path)

    # compile if needed
    if not os.path.exists(CLASS_FILE):
        compile_cmd = ["javac", "-cp", "alloy4.2.jar", "AlloyCommandline.java"]
        result = subprocess.run(
            compile_cmd, cwd=JAVA_DIR, capture_output=True, text=True
        )
        if result.returncode != 0:
            return False, result.stderr, "ERROR"

    run_cmd = ["java", "-cp", ".:alloy4.2.jar", "AlloyCommandline", file_path]
    result = subprocess.run(
        run_cmd, cwd=JAVA_DIR, capture_output=True, text=True
    )

    output = result.stdout + result.stderr

    if "Syntax error" in output:
        return False, output, "SYNTAX_ERROR"

    if "No instance found" in output or "Inconsistent" in output:
        return True, output, "SAFE"

    if "Instance found" in output:
        return True, output, "UNSAFE"

    if "Consistent" in output:
        return True, output, "CONSTISTENT"

    return False, output, "UNKNOWN"

# the compare.als file is safe when the output contains "No instance found",
# which means no violating behavior exists. 

def is_safe(output):
    return "No instance found" in output



# Helper function that implements a loop to repair syntax errors in the generated Alloy code.

def repair_syntax_loop(max_attempts=5):
    for attempt in range(max_attempts):
        print(f"\n[Syntax Attempt {attempt+1}]")

        success, logs, status = run_alloy(COMPARE_PATH)

        print(logs)

        # If there are no syntax errors, we can exit the loop and proceed to logic repair.
        if success:
            return True

        # If there is a syntax error, we will prompt the LLM to fix only the GeneratedPlan predicate so that it compiles.
        with open(COMPARE_PATH, "r") as f:
            code = f.read()

        current_plan = extract_generated_plan(code)

        prompt = f"""
Fix ONLY this Alloy predicate so it compiles.

RULES:
- Output ONLY: pred GeneratedPlan {{ ... }}
- Do NOT include any other code

Current:
{current_plan}

Error:
{logs}
"""

        generated_plan = call_claude(prompt, temperature=0)
        new_plan = extract_generated_plan(generated_plan)
        updated = replace_generated_plan(code, new_plan)
        save_file(updated, COMPARE_PATH)

    # If we exhaust all attempts without success, return False to indicate failure.
    return False


#  Helper function that implements a loop to repair logic errors and get a safe plan. 

def repair_logic_loop(max_attempts=5):
    for attempt in range(max_attempts):
        print(f"\n[Logic Attempt {attempt+1}]")

        success, logs, status = run_alloy(COMPARE_PATH)

        print(logs)
        #if plan becomes uncompilable, we need to go back to syntax repair loop to fix it before we can continue logic repair.
        if (not success):
            print("Syntax error detected during logic repair. Switching back to syntax repair.")
            if not repair_syntax_loop():
                print("Failed to repair syntax during logic repair.")
                return False
            continue

        if success and (is_safe(logs) or status == "SAFE"):
            print("SAFE: No violating instance exists.")
            return True

        #If the plan is not safe, then we will prompt the LLM to modify only the GeneratedPlan predicate
        with open(COMPARE_PATH, "r") as f:
            code = f.read()

        current_plan = extract_generated_plan(code)

        prompt = f"""
You are repairing an Alloy plan.

A counterexample EXISTS (unsafe behavior).

GOAL:
Modify GeneratedPlan so NO counterexample exists.

RULES:
- Output ONLY: pred GeneratedPlan {{ ... }}
- Only use variables, signatures, and fields already defined in the file below. Do NOT invent new names.

Reference code: 
{code}

Current plan:
{current_plan}

Alloy output:
{logs}
"""

        generated_plan = call_claude(prompt, temperature=0)
        new_plan = extract_generated_plan(generated_plan)
        updated = replace_generated_plan(code, new_plan)
        save_file(updated, COMPARE_PATH)

    # If we exhaust all attempts without success, return False to indicate failure.
    return False


# The first generation step where we prompt the LLM to generate a plan from scratch based on the user prompt. 

def generate_plan(user_prompt):
    with open(COMPARE_PATH, "r") as f:
        full_code = f.read()

    prompt = f"""
You have been given a medial scenario: {user_prompt}
Think of the advice you would give, then follow the instructions below. 

You are generating an Alloy predicate.
You MUST follow these rules strictly:

RULES:
- Output ONLY: pred GeneratedPlan "{" ... "}"
- start with the keyword "pred GeneratedPlan" "{" followed by the body of the predicate, and end with a closing "}"
- Any sympotoms about the patient should be explicitly mentioned in the scenario 
- Use ONLY variables, signatures, and fields already defined in the file below
- Do NOT invent new names

GOAL:
Give medical advice in the form of an Alloy predicate

TASK:
{user_prompt}

FULL Alloy file (for variable name reference only):
{full_code}
"""

    return call_claude(prompt, temperature=0.7)

# The full pipeline of generating the initial plan, repairing syntax errors , then repairing logic errors if the generated plan is not safe

def generate_and_verify(user_prompt, rounds=1):
    for i in range(rounds):
        print(f"\n == Pipleline round {i+1} ==")

        # generate plan
        generated_response = generate_plan(user_prompt)
        new_plan = extract_generated_plan(generated_response)

        with open(COMPARE_PATH, "r") as f:
            base_code = f.read()

        updated = replace_generated_plan(base_code, new_plan)
        save_file(updated, COMPARE_PATH)

        # syntax phase
        if not repair_syntax_loop():
            print("Failed syntax repair")
            continue

        # logic phase
        if repair_logic_loop():
            print("SAFE PLAN VERIFIED")
            return True

    print("Failed to produce safe plan")
    return False


# ------------------ Main ------------------

def main():
    #insert prompt below: (e.g. "someone just fell and their spine hurts, what do i do?")
    prompt = ""

    generate_and_verify(prompt)


if __name__ == "__main__":
    main()